### ISSUE TITLE
Segmentation fault in CUDA GDB 10.2

### ISSUE THREAD

**Issue by Pupillen** [NVIDIA/cuda-gdb#12] opened 2023-08-04 16:11 UTC
While debugging a CUDA application with CUDA GDB 10.2, the debugger crashes with a segmentation fault. Further debugging prompts the following internal error:
Thread 1 "plan_manager" received signal SIGSEGV, Segmentation fault.
cuda-gdb/10.2/gdb/regcache.c:171: internal-error: int register_size(gdbarch*, int): Assertion `regnum >= 0 && regnum < gdbarch_num_cooked_regs (gdbarch)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) [answered Y; input not from terminal]

This is a bug, please report it.  For instructions, see:
<https://www.gnu.org/software/gdb/bugs/>.
OS: [Ubuntu 20.04]
CUDA version: [11.8]
GPU Model: [e.g., Nvidia RTX 2060]

```[tasklist]
### Tasks
```

**Comment by agontarek** [comment] 2023-09-18 16:22
@Pupillen is there any way you can submit a reproducer? I would like to also check if this has been fixed by the latest release of CUDA-GDB in the CUDA Toolkit 12.2.

**Comment by agontarek** [comment] 2024-03-20 19:05
Closing as unable to reproduce. Please provide a reproducer and reopen if this is still encountered with the latest CTK release.

**Closed as not planned** 2024-03-20 19:05 UTC
Labels: bug
